### ISSUE TITLE
Lando drush si minimal -y failed

### ISSUE THREAD

**Issue by vimmacs** [wunderio/next-drupal-starterkit#183]
## environment
- Macbook M1Pro
- Lando Latest version with its built-in Docker
- A project folder named `tlca`
## operation
- copy setup.sh to `tlca`.
- run ./setup.sh or ./setup.sh -c.
## Issue
Did you mean ssh?
Command lando drush si minimal -y failed.
<img width="638" alt="install-error" src="https://github.com/wunderio/next-drupal-starterkit/assets/66717650/9030eefc-7682-48a7-ae53-88efc7967784">

**Comment by vermario** [comment]
haven't seen this before :)

I wonder about the step "copying `setup.sh` into folder"... the idea is that you checkout the project into any directory (but the whole project) and then run that command. (it's just a series of commands, if does not do anything else).

**Comment by vimmacs** [comment]
Thanks a lot @vermario , it worked!
